# Generated by Django 2.2.2 on 2019-09-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvideo',
            name='uID',
            field=models.CharField(default='', max_length=10),
        ),
    ]
